package main

// AvroPatterns contains all phonetic conversion rules
var AvroPatterns = []Pattern{
	{Find: "bhl", Replace: "ভ্ল"},
	{Find: "psh", Replace: "পশ"},
	{Find: "bdh", Replace: "ব্ধ"},
	{Find: "bj", Replace: "ব্জ"},
	{Find: "bd", Replace: "ব্দ"},
	{Find: "bb", Replace: "ব্ব"},
	{Find: "bl", Replace: "ব্ল"},
	{Find: "bh", Replace: "ভ"},
	{Find: "vl", Replace: "ভ্ল"},
	{Find: "b", Replace: "ব"},
	{Find: "v", Replace: "ভ"},
	{Find: "cNG", Replace: "চ্ঞ"},
	{Find: "cch", Replace: "চ্ছ"},
	{Find: "cc", Replace: "চ্চ"},
	{Find: "ch", Replace: "ছ"},
	{Find: "c", Replace: "চ"},
	{Find: "dhn", Replace: "ধ্ন"},
	{Find: "dhm", Replace: "ধ্ম"},
	{Find: "dgh", Replace: "দ্ঘ"},
	{Find: "ddh", Replace: "দ্ধ"},
	{Find: "dbh", Replace: "দ্ভ"},
	{Find: "dv", Replace: "দ্ভ"},
	{Find: "dm", Replace: "দ্ম"},
	{Find: "DD", Replace: "ড্ড"},
	{Find: "Dh", Replace: "ঢ"},
	{Find: "dh", Replace: "ধ"},
	{Find: "dg", Replace: "দ্গ"},
	{Find: "dd", Replace: "দ্দ"},
	{Find: "D", Replace: "ড"},
	{Find: "d", Replace: "দ"},
	{Find: "...", Replace: "..."},
	{Find: ".`", Replace: "."},
	{Find: "..", Replace: "।।"},
	{Find: ".", Replace: "।"},
	{Find: "ghn", Replace: "ঘ্ন"},
	{Find: "Ghn", Replace: "ঘ্ন"},
	{Find: "gdh", Replace: "গ্ধ"},
	{Find: "Gdh", Replace: "গ্ধ"},
	{Find: "gN", Replace: "গ্ণ"},
	{Find: "GN", Replace: "গ্ণ"},
	{Find: "gn", Replace: "গ্ন"},
	{Find: "Gn", Replace: "গ্ন"},
	{Find: "gm", Replace: "গ্ম"},
	{Find: "Gm", Replace: "গ্ম"},
	{Find: "gl", Replace: "গ্ল"},
	{Find: "Gl", Replace: "গ্ল"},
	{Find: "gg", Replace: "জ্ঞ"},
	{Find: "GG", Replace: "জ্ঞ"},
	{Find: "Gg", Replace: "জ্ঞ"},
	{Find: "gG", Replace: "জ্ঞ"},
	{Find: "gh", Replace: "ঘ"},
	{Find: "Gh", Replace: "ঘ"},
	{Find: "g", Replace: "গ"},
	{Find: "G", Replace: "গ"},
	{Find: "hN", Replace: "হ্ণ"},
	{Find: "hn", Replace: "হ্ন"},
	{Find: "hm", Replace: "হ্ম"},
	{Find: "hl", Replace: "হ্ল"},
	{Find: "h", Replace: "হ"},
	{Find: "jjh", Replace: "জ্ঝ"},
	{Find: "jNG", Replace: "জ্ঞ"},
	{Find: "jh", Replace: "ঝ"},
	{Find: "jj", Replace: "জ্জ"},
	{Find: "j", Replace: "জ"},
	{Find: "J", Replace: "জ"},
	{Find: "kkhN", Replace: "ক্ষ্ণ"},
	{Find: "kShN", Replace: "ক্ষ্ণ"},
	{Find: "kkhm", Replace: "ক্ষ্ম"},
	{Find: "kShm", Replace: "ক্ষ্ম"},
	{Find: "kxN", Replace: "ক্ষ্ণ"},
	{Find: "kxm", Replace: "ক্ষ্ম"},
	{Find: "kkh", Replace: "ক্ষ"},
	{Find: "kSh", Replace: "ক্ষ"},
	{Find: "ksh", Replace: "কশ"},
	{Find: "kx", Replace: "ক্ষ"},
	{Find: "kk", Replace: "ক্ক"},
	{Find: "kT", Replace: "ক্ট"},
	{Find: "kt", Replace: "ক্ত"},
	{Find: "kl", Replace: "ক্ল"},
	{Find: "ks", Replace: "ক্স"},
	{Find: "kh", Replace: "খ"},
	{Find: "k", Replace: "ক"},
	{Find: "lbh", Replace: "ল্ভ"},
	{Find: "ldh", Replace: "ল্ধ"},
	{Find: "lkh", Replace: "লখ"},
	{Find: "lgh", Replace: "লঘ"},
	{Find: "lph", Replace: "লফ"},
	{Find: "lk", Replace: "ল্ক"},
	{Find: "lg", Replace: "ল্গ"},
	{Find: "lT", Replace: "ল্ট"},
	{Find: "lD", Replace: "ল্ড"},
	{Find: "lp", Replace: "ল্প"},
	{Find: "lv", Replace: "ল্ভ"},
	{Find: "lm", Replace: "ল্ম"},
	{Find: "ll", Replace: "ল্ল"},
	{Find: "lb", Replace: "ল্ব"},
	{Find: "l", Replace: "ল"},
	{Find: "mth", Replace: "ম্থ"},
	{Find: "mph", Replace: "ম্ফ"},
	{Find: "mbh", Replace: "ম্ভ"},
	{Find: "mpl", Replace: "মপ্ল"},
	{Find: "mn", Replace: "ম্ন"},
	{Find: "mp", Replace: "ম্প"},
	{Find: "mv", Replace: "ম্ভ"},
	{Find: "mm", Replace: "ম্ম"},
	{Find: "ml", Replace: "ম্ল"},
	{Find: "mb", Replace: "ম্ব"},
	{Find: "mf", Replace: "ম্ফ"},
	{Find: "m", Replace: "ম"},
	{Find: "0", Replace: "০"},
	{Find: "1", Replace: "১"},
	{Find: "2", Replace: "২"},
	{Find: "3", Replace: "৩"},
	{Find: "4", Replace: "৪"},
	{Find: "5", Replace: "৫"},
	{Find: "6", Replace: "৬"},
	{Find: "7", Replace: "৭"},
	{Find: "8", Replace: "৮"},
	{Find: "9", Replace: "৯"},
	{Find: "NgkSh", Replace: "ঙ্ক্ষ"},
	{Find: "Ngkkh", Replace: "ঙ্ক্ষ"},
	{Find: "NGch", Replace: "ঞ্ছ"},
	{Find: "Nggh", Replace: "ঙ্ঘ"},
	{Find: "Ngkh", Replace: "ঙ্খ"},
	{Find: "NGjh", Replace: "ঞ্ঝ"},
	{Find: "ngOU", Replace: "ঙ্গৌ"},
	{Find: "ngOI", Replace: "ঙ্গৈ"},
	{Find: "Ngkx", Replace: "ঙ্ক্ষ"},
	{Find: "NGc", Replace: "ঞ্চ"},
	{Find: "nch", Replace: "ঞ্ছ"},
	{Find: "njh", Replace: "ঞ্ঝ"},
	{Find: "ngh", Replace: "ঙ্ঘ"},
	{Find: "Ngk", Replace: "ঙ্ক"},
	{Find: "Ngx", Replace: "ঙ্ষ"},
	{Find: "Ngg", Replace: "ঙ্গ"},
	{Find: "Ngm", Replace: "ঙ্ম"},
	{Find: "NGj", Replace: "ঞ্জ"},
	{Find: "ndh", Replace: "ন্ধ"},
	{Find: "nTh", Replace: "ন্ঠ"},
	{Find: "NTh", Replace: "ণ্ঠ"},
	{Find: "nth", Replace: "ন্থ"},
	{Find: "nkh", Replace: "ঙ্খ"},
	{Find: "ngo", Replace: "ঙ্গ"},
	{Find: "nga", Replace: "ঙ্গা"},
	{Find: "ngi", Replace: "ঙ্গি"},
	{Find: "ngI", Replace: "ঙ্গী"},
	{Find: "ngu", Replace: "ঙ্গু"},
	{Find: "ngU", Replace: "ঙ্গূ"},
	{Find: "nge", Replace: "ঙ্গে"},
	{Find: "ngO", Replace: "ঙ্গো"},
	{Find: "NDh", Replace: "ণ্ঢ"},
	{Find: "nsh", Replace: "নশ"},
	{Find: "Ngr", Replace: "ঙর"},
	{Find: "NGr", Replace: "ঞর"},
	{Find: "ngr", Replace: "ংর"},
	{Find: "nj", Replace: "ঞ্জ"},
	{Find: "Ng", Replace: "ঙ"},
	{Find: "NG", Replace: "ঞ"},
	{Find: "nk", Replace: "ঙ্ক"},
	{Find: "ng", Replace: "ং"},
	{Find: "nn", Replace: "ন্ন"},
	{Find: "NN", Replace: "ণ্ণ"},
	{Find: "Nn", Replace: "ণ্ন"},
	{Find: "nm", Replace: "ন্ম"},
	{Find: "Nm", Replace: "ণ্ম"},
	{Find: "nd", Replace: "ন্দ"},
	{Find: "nT", Replace: "ন্ট"},
	{Find: "NT", Replace: "ণ্ট"},
	{Find: "nD", Replace: "ন্ড"},
	{Find: "ND", Replace: "ণ্ড"},
	{Find: "nt", Replace: "ন্ত"},
	{Find: "ns", Replace: "ন্স"},
	{Find: "nc", Replace: "ঞ্চ"},
	{Find: "n", Replace: "ন"},
	{Find: "N", Replace: "ণ"},
	{Find: "OI`", Replace: "ৈ"},
	{Find: "OU`", Replace: "ৌ"},
	{Find: "O`", Replace: "ো"},
	{
		Find:    "OI",
		Replace: "ৈ",
		Rules: []Rule{
			{
				Matches: []Match{
					{Type: "prefix", Scope: "consonant", Negative: true},
				},
				Replace: "ঐ",
			},
			{
				Matches: []Match{
					{Type: "prefix", Scope: "punctuation"},
				},
				Replace: "ঐ",
			},
		},
	},
	{
		Find:    "OU",
		Replace: "ৌ",
		Rules: []Rule{
			{
				Matches: []Match{
					{Type: "prefix", Scope: "consonant", Negative: true},
				},
				Replace: "ঔ",
			},
			{
				Matches: []Match{
					{Type: "prefix", Scope: "punctuation"},
				},
				Replace: "ঔ",
			},
		},
	},
	{
		Find:    "O",
		Replace: "ো",
		Rules: []Rule{
			{
				Matches: []Match{
					{Type: "prefix", Scope: "consonant", Negative: true},
				},
				Replace: "ও",
			},
			{
				Matches: []Match{
					{Type: "prefix", Scope: "punctuation"},
				},
				Replace: "ও",
			},
		},
	},
	{Find: "phl", Replace: "ফ্ল"},
	{Find: "pT", Replace: "প্ট"},
	{Find: "pt", Replace: "প্ত"},
	{Find: "pn", Replace: "প্ন"},
	{Find: "pp", Replace: "প্প"},
	{Find: "pl", Replace: "প্ল"},
	{Find: "ps", Replace: "প্স"},
	{Find: "ph", Replace: "ফ"},
	{Find: "fl", Replace: "ফ্ল"},
	{Find: "f", Replace: "ফ"},
	{Find: "p", Replace: "প"},
	{Find: "rri`", Replace: "ৃ"},
	{
		Find:    "rri",
		Replace: "ৃ",
		Rules: []Rule{
			{
				Matches: []Match{
					{Type: "prefix", Scope: "consonant", Negative: true},
				},
				Replace: "ঋ",
			},
			{
				Matches: []Match{
					{Type: "prefix", Scope: "punctuation"},
				},
				Replace: "ঋ",
			},
		},
	},
	{Find: "rrZ", Replace: "রর‍্য"},
	{Find: "rry", Replace: "রর‍্য"},
	{
		Find:    "rZ",
		Replace: "র‍্য",
		Rules: []Rule{
			{
				Matches: []Match{
					{Type: "prefix", Scope: "consonant"},
					{Type: "prefix", Scope: "exact", Value: "r", Negative: true},
					{Type: "prefix", Scope: "exact", Value: "y", Negative: true},
					{Type: "prefix", Scope: "exact", Value: "w", Negative: true},
					{Type: "prefix", Scope: "exact", Value: "x", Negative: true},
				},
				Replace: "্র্য",
			},
		},
	},
	{
		Find:    "ry",
		Replace: "র‍্য",
		Rules: []Rule{
			{
				Matches: []Match{
					{Type: "prefix", Scope: "consonant"},
					{Type: "prefix", Scope: "exact", Value: "r", Negative: true},
					{Type: "prefix", Scope: "exact", Value: "y", Negative: true},
					{Type: "prefix", Scope: "exact", Value: "w", Negative: true},
					{Type: "prefix", Scope: "exact", Value: "x", Negative: true},
				},
				Replace: "্র্য",
			},
		},
	},
	{
		Find:    "rr",
		Replace: "রর",
		Rules: []Rule{
			{
				Matches: []Match{
					{Type: "prefix", Scope: "consonant", Negative: true},
					{Type: "suffix", Scope: "vowel", Negative: true},
					{Type: "suffix", Scope: "exact", Value: "r", Negative: true},
					{Type: "suffix", Scope: "punctuation", Negative: true},
				},
				Replace: "র্",
			},
			{
				Matches: []Match{
					{Type: "prefix", Scope: "consonant"},
					{Type: "prefix", Scope: "exact", Value: "r", Negative: true},
				},
				Replace: "্রর",
			},
		},
	},
	{Find: "Rg", Replace: "ড়্গ"},
	{Find: "Rh", Replace: "ঢ়"},
	{Find: "R", Replace: "ড়"},
	{
		Find:    "r",
		Replace: "র",
		Rules: []Rule{
			{
				Matches: []Match{
					{Type: "prefix", Scope: "consonant"},
					{Type: "prefix", Scope: "exact", Value: "r", Negative: true},
					{Type: "prefix", Scope: "exact", Value: "y", Negative: true},
					{Type: "prefix", Scope: "exact", Value: "w", Negative: true},
					{Type: "prefix", Scope: "exact", Value: "x", Negative: true},
					{Type: "prefix", Scope: "exact", Value: "Z", Negative: true},
				},
				Replace: "্র",
			},
		},
	},
	{Find: "shch", Replace: "শ্ছ"},
	{Find: "ShTh", Replace: "ষ্ঠ"},
	{Find: "Shph", Replace: "ষ্ফ"},
	{Find: "Sch", Replace: "শ্ছ"},
	{Find: "skl", Replace: "স্ক্ল"},
	{Find: "skh", Replace: "স্খ"},
	{Find: "sth", Replace: "স্থ"},
	{Find: "sph", Replace: "স্ফ"},
	{Find: "shc", Replace: "শ্চ"},
	{Find: "sht", Replace: "শ্ত"},
	{Find: "shn", Replace: "শ্ন"},
	{Find: "shm", Replace: "শ্ম"},
	{Find: "shl", Replace: "শ্ল"},
	{Find: "Shk", Replace: "ষ্ক"},
	{Find: "ShT", Replace: "ষ্ট"},
	{Find: "ShN", Replace: "ষ্ণ"},
	{Find: "Shp", Replace: "ষ্প"},
	{Find: "Shf", Replace: "ষ্ফ"},
	{Find: "Shm", Replace: "ষ্ম"},
	{Find: "spl", Replace: "স্প্ল"},
	{Find: "sk", Replace: "স্ক"},
	{Find: "Sc", Replace: "শ্চ"},
	{Find: "sT", Replace: "স্ট"},
	{Find: "st", Replace: "স্ত"},
	{Find: "sn", Replace: "স্ন"},
	{Find: "sp", Replace: "স্প"},
	{Find: "sf", Replace: "স্ফ"},
	{Find: "sm", Replace: "স্ম"},
	{Find: "sl", Replace: "স্ল"},
	{Find: "sh", Replace: "শ"},
	{Find: "Sc", Replace: "শ্চ"},
	{Find: "St", Replace: "শ্ত"},
	{Find: "Sn", Replace: "শ্ন"},
	{Find: "Sm", Replace: "শ্ম"},
	{Find: "Sl", Replace: "শ্ল"},
	{Find: "Sh", Replace: "ষ"},
	{Find: "s", Replace: "স"},
	{Find: "S", Replace: "শ"},
	{Find: "oo`", Replace: "ু"},
	{
		Find:    "oo",
		Replace: "ু",
		Rules: []Rule{
			{
				Matches: []Match{
					{Type: "prefix", Scope: "consonant", Negative: true},
					{Type: "suffix", Scope: "exact", Value: "`", Negative: true},
				},
				Replace: "উ",
			},
			{
				Matches: []Match{
					{Type: "prefix", Scope: "punctuation"},
					{Type: "suffix", Scope: "exact", Value: "`", Negative: true},
				},
				Replace: "উ",
			},
		},
	},
	{Find: "o`", Replace: ""},
	{Find: "oZ", Replace: "অ্য"},
	{
		Find:    "o",
		Replace: "",
		Rules: []Rule{
			{
				Matches: []Match{
					{Type: "prefix", Scope: "vowel"},
					{Type: "prefix", Scope: "exact", Value: "o", Negative: true},
				},
				Replace: "ও",
			},
			{
				Matches: []Match{
					{Type: "prefix", Scope: "vowel"},
					{Type: "prefix", Scope: "exact", Value: "o"},
				},
				Replace: "অ",
			},
			{
				Matches: []Match{
					{Type: "prefix", Scope: "punctuation"},
				},
				Replace: "অ",
			},
		},
	},
	{Find: "tth", Replace: "ত্থ"},
	{Find: "t``", Replace: "ৎ"},
	{Find: "TT", Replace: "ট্ট"},
	{Find: "Tm", Replace: "ট্ম"},
	{Find: "Th", Replace: "ঠ"},
	{Find: "tn", Replace: "ত্ন"},
	{Find: "tm", Replace: "ত্ম"},
	{Find: "th", Replace: "থ"},
	{Find: "tt", Replace: "ত্ত"},
	{Find: "T", Replace: "ট"},
	{Find: "t", Replace: "ত"},
	{Find: "aZ", Replace: "অ্যা"},
	{Find: "AZ", Replace: "অ্যা"},
	{Find: "a`", Replace: "া"},
	{Find: "A`", Replace: "া"},
	{
		Find:    "a",
		Replace: "া",
		Rules: []Rule{
			{
				Matches: []Match{
					{Type: "prefix", Scope: "punctuation"},
					{Type: "suffix", Scope: "exact", Value: "`", Negative: true},
				},
				Replace: "আ",
			},
			{
				Matches: []Match{
					{Type: "prefix", Scope: "consonant", Negative: true},
					{Type: "prefix", Scope: "exact", Value: "a", Negative: true},
					{Type: "suffix", Scope: "exact", Value: "`", Negative: true},
				},
				Replace: "য়া",
			},
			{
				Matches: []Match{
					{Type: "prefix", Scope: "exact", Value: "a"},
					{Type: "suffix", Scope: "exact", Value: "`", Negative: true},
				},
				Replace: "আ",
			},
		},
	},
	{Find: "i`", Replace: "ি"},
	{
		Find:    "i",
		Replace: "ি",
		Rules: []Rule{
			{
				Matches: []Match{
					{Type: "prefix", Scope: "consonant", Negative: true},
					{Type: "suffix", Scope: "exact", Value: "`", Negative: true},
				},
				Replace: "ই",
			},
			{
				Matches: []Match{
					{Type: "prefix", Scope: "punctuation"},
					{Type: "suffix", Scope: "exact", Value: "`", Negative: true},
				},
				Replace: "ই",
			},
		},
	},
	{Find: "I`", Replace: "ী"},
	{
		Find:    "I",
		Replace: "ী",
		Rules: []Rule{
			{
				Matches: []Match{
					{Type: "prefix", Scope: "consonant", Negative: true},
					{Type: "suffix", Scope: "exact", Value: "`", Negative: true},
				},
				Replace: "ঈ",
			},
			{
				Matches: []Match{
					{Type: "prefix", Scope: "punctuation"},
					{Type: "suffix", Scope: "exact", Value: "`", Negative: true},
				},
				Replace: "ঈ",
			},
		},
	},
	{Find: "u`", Replace: "ু"},
	{
		Find:    "u",
		Replace: "ু",
		Rules: []Rule{
			{
				Matches: []Match{
					{Type: "prefix", Scope: "consonant", Negative: true},
					{Type: "suffix", Scope: "exact", Value: "`", Negative: true},
				},
				Replace: "উ",
			},
			{
				Matches: []Match{
					{Type: "prefix", Scope: "punctuation"},
					{Type: "suffix", Scope: "exact", Value: "`", Negative: true},
				},
				Replace: "উ",
			},
		},
	},
	{Find: "U`", Replace: "ূ"},
	{
		Find:    "U",
		Replace: "ূ",
		Rules: []Rule{
			{
				Matches: []Match{
					{Type: "prefix", Scope: "consonant", Negative: true},
					{Type: "suffix", Scope: "exact", Value: "`", Negative: true},
				},
				Replace: "ঊ",
			},
			{
				Matches: []Match{
					{Type: "prefix", Scope: "punctuation"},
					{Type: "suffix", Scope: "exact", Value: "`", Negative: true},
				},
				Replace: "ঊ",
			},
		},
	},
	{Find: "ee`", Replace: "ী"},
	{
		Find:    "ee",
		Replace: "ী",
		Rules: []Rule{
			{
				Matches: []Match{
					{Type: "prefix", Scope: "consonant", Negative: true},
					{Type: "suffix", Scope: "exact", Value: "`", Negative: true},
				},
				Replace: "ঈ",
			},
			{
				Matches: []Match{
					{Type: "prefix", Scope: "punctuation"},
					{Type: "suffix", Scope: "exact", Value: "`", Negative: true},
				},
				Replace: "ঈ",
			},
		},
	},
	{Find: "e`", Replace: "ে"},
	{
		Find:    "e",
		Replace: "ে",
		Rules: []Rule{
			{
				Matches: []Match{
					{Type: "prefix", Scope: "consonant", Negative: true},
					{Type: "suffix", Scope: "exact", Value: "`", Negative: true},
				},
				Replace: "এ",
			},
			{
				Matches: []Match{
					{Type: "prefix", Scope: "punctuation"},
					{Type: "suffix", Scope: "exact", Value: "`", Negative: true},
				},
				Replace: "এ",
			},
		},
	},
	{Find: "z", Replace: "য"},
	{Find: "Z", Replace: "্য"},
	{
		Find:    "y",
		Replace: "্য",
		Rules: []Rule{
			{
				Matches: []Match{
					{Type: "prefix", Scope: "consonant", Negative: true},
					{Type: "prefix", Scope: "punctuation", Negative: true},
				},
				Replace: "য়",
			},
			{
				Matches: []Match{
					{Type: "prefix", Scope: "punctuation"},
				},
				Replace: "ইয়",
			},
		},
	},
	{Find: "Y", Replace: "য়"},
	{Find: "q", Replace: "ক"},
	{
		Find:    "w",
		Replace: "ও",
		Rules: []Rule{
			{
				Matches: []Match{
					{Type: "prefix", Scope: "punctuation"},
					{Type: "suffix", Scope: "vowel"},
				},
				Replace: "ওয়",
			},
			{
				Matches: []Match{
					{Type: "prefix", Scope: "consonant"},
				},
				Replace: "্ব",
			},
		},
	},
	{
		Find:    "x",
		Replace: "ক্স",
		Rules: []Rule{
			{
				Matches: []Match{
					{Type: "prefix", Scope: "punctuation"},
				},
				Replace: "এক্স",
			},
		},
	},
	{Find: ":`", Replace: ":"},
	{Find: ":", Replace: "ঃ"},
	{Find: "^`", Replace: "^"},
	{Find: "^", Replace: "ঁ"},
	{Find: ",,", Replace: "্‌"},
	{Find: ",", Replace: ","},
	{Find: "$", Replace: "৳"},
	{Find: "`", Replace: ""},
}

const AvroVowel = "aeiou"
const AvroConsonant = "bcdfghjklmnpqrstvwxyz"
const AvroCaseSensitive = "oiudgjnrstyz"